### ISSUE TITLE
Fix bug in DB

### ISSUE THREAD

**Issue by vainbaum** [TechnionYearlyProject/Exam-Scheduler#108]
db.exception.InvalidDatabase: Invalid XML file constraintsA.xml :
org.xml.sax.SAXParseException; systemId: file:/home/mvainbau/YearProject/Exam-Scheduler/db/2017_winter_test/constraintsA.xml; lineNumber: 5; columnNumber: 15; cvc-complex-type.2.4.a: Invalid content was found starting with element 'date'. One of '{start_date}' is expected

**Comment by rephaelaz** [comment]
Fixed
