### ISSUE TITLE
Main calender screen - build calenders for Moed A and B.

### ISSUE THREAD

**Issue by Roia5** [TechnionYearlyProject/Exam-Scheduler#4]

**Comment by tanyabrokhman** [comment]
consider breaking this into 2 issues

**Comment by Roia5** [comment]
@tanyabrokhman Can you guide us which 2 issues? Since both moed A and moed B have the same calendar layout we thought we only need 1 issue. Thanks

**Comment by tanyabrokhman** [comment]
I thought that moed a and moed b can be 2 different issues but if its the
same for both you're right in making this one issue

**Comment by TalGelber** [comment]
@tanyabrokhman  as you said we divided the issue to #47-#50
