### ISSUE TITLE
Main Screen - when changing to overlapped dates do not cancel day lock 

### ISSUE THREAD

**Issue by TalGelber** [TechnionYearlyProject/Exam-Scheduler#45]
example:
if in Moed A defined to dates 1/2/2018 until 30/2/2018 and user locked day 15/2/2018,
when user redifine Moed A dates to 10/2/18 until 30/2/2018 then keep the day 15/2/2018 locked.

**Comment by Roia5** [comment]
I think you should also throw an error message when the user tries to enter illegal dates, for example:
10/2/2018 until 5/2/2018 is an invalid choice.

**Comment by dorbartov** [comment]
Not implemented this semester.
