### ISSUE TITLE
change course_id to string

### ISSUE THREAD

**Issue by dorbartov** [TechnionYearlyProject/Exam-Scheduler#53]
consider changing course_id from int to string in order to handle course numbers starting with 0.

**Comment by ucfbader** [comment]
changing course_id to String will lead to few changes in some tests and classes, especially in the DB.

**Comment by rephaelaz** [comment]
You can use String.format() to format an integer with 0's at the beginning. No need to change the DB for this

**Comment by Roia5** [comment]
Decided to leave the course_id as an Integer.
