### ISSUE TITLE
write conflict Courses to DB.

### ISSUE THREAD

**Issue by ucfbader** [TechnionYearlyProject/Exam-Scheduler#98]
the user can define new conflicts that may not appear at our initial db. In order to allow loading previous Schedules we need to write and load this extra data.

**Comment by rephaelaz** [comment]
For now, Semester simply has a public field "conflicts" and only handle data loading/serilization. Modifying the field is up to Logic

**Comment by ucfbader** [comment]
DBNotifier class deals with this
